### ISSUE TITLE
php-parser version required is old and conflicting(?)

### ISSUE THREAD

**Issue by thekabal** [edsonmedina/php_testability#76]
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: nikic/php-parser[v3.0.6, v1.4.1].
    - Can only install one of: nikic/php-parser[v1.4.1, v3.0.6].
    - Can only install one of: nikic/php-parser[v1.4.1, v3.0.6].
    - edsonmedina/php_testability dev-master requires nikic/php-parser 1.4.1 -> satisfiable by nikic/php-parser[v1.4.1].
    - Installation request for edsonmedina/php_testability dev-master -> satisfiable by edsonmedina/php_testability[dev-master].
    - Installation request for nikic/php-parser (locked at v3.0.6) -> satisfiable by nikic/php-parser[v3.0.6].

**Comment by edsonmedina** [comment]
Can you please explain what are you trying to do?

**Comment by thekabal** [comment]
Thanks for the reply. In trying to install php_testability, I ran:

composer require edsonmedina/php_testability "dev-master"

The output is seen above. It seems there is a conflict, perhaps due to the pinned version of php-parser required?

**Comment by bingalls** [comment]
@edsonmedina It is not possible to run the latest phpstan/phpstan v0.7 in the same composer project as (current) testability, as it requires a recent version of nikic/php-parser. Phpstan v0.1 is not useful.

**Comment by edsonmedina** [comment]
This should be fixed now.

**Comment by thekabal** [comment]
Awesome! It does indeed install cleanly. Many thanks!!
