### ISSUE TITLE
Recoverable fatal error: Object of class ...Variable could not be converted to string

### ISSUE THREAD

**Issue by thekabal** [edsonmedina/php_testability#77]
PHP_Testability by Edson Medina
Analysing code on "tki"...
..........................................................................................PHP Recoverable fatal error:  Object of class PhpParser\Node\Expr\Variable could not be converted to string in tki/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 76

:(

Not sure the cause for this error, please let me know if I can help further.

**Comment by edsonmedina** [comment]
I might have fixed that in #80, can you try now?

**Comment by thekabal** [comment]
Seems slightly different now, but still not functional.

Package operations: 0 installs, 1 update, 0 removals
  - Updating edsonmedina/php_testability dev-master (97f6172 => 7a77d1a):  Checking out 7a77d1ac33

PHP_Testability by Edson Medina
Analysing code on "tki"...
..........................................................................................PHP Recoverable fatal error:  Object of class PhpParser\Node\Expr\Variable could not be converted to string in tki/vendor/edsonmedina/php_testability/src/NodeWrapper.php on line 81

**Comment by edsonmedina** [comment]
`NodeWrapper`'s code is really crappy and I can't really be sure I fixed it without having a copy of your files, so I'm going to ask you to update php_testability and try again.

**Comment by edsonmedina** [comment]
Might have been fixed in #81. Please check now.

**Comment by thekabal** [comment]
- Updating edsonmedina/php_testability dev-master (6642753 => e9def94):
Checking out e9def94134

PHP_Testability by Edson Medina
Analysing code on "/var/www/html/tki"...
...............................................................................................................................PHP
Recoverable fatal error:  Object of class PhpParser\Node\Expr\ArrayDimFetch
could not be converted to string in
/var/www/html/tki/vendor/edsonmedina/php_testability/src/NodeWrapper.php on
line 34


You are welcome to test against my code. https://github.com/thekabal/tki/ ,
should be as easy as git clone, composer install/update, and then attempt
to run testability against it.

Hope that helps!

**Comment by edsonmedina** [comment]
Fixed now, thanks!
