### ISSUE TITLE
parent::run() reported as static call.

### ISSUE THREAD

**Issue by Archanium** [edsonmedina/php_testability#78]
Hi

I've discovered that parent::run() is reported as a static call, I don't think this should be the case (if the part in front is parent just assume it's not a static call?)

I'll gladly try to fix this myself and submit a Pull Request for it.

**Comment by edsonmedina** [comment]
I'm not sure what you're talking about, in which file is this?

But yes, please submit a PR.

**Comment by Archanium** [comment]
There is a pull request for this here: #79

**Comment by Archanium** [comment]
and it is any parent:: calls that are reported as static calls, in my case it was the run method, that's the reason for the title. Sorry about that being a bit misleading.

**Comment by edsonmedina** [comment]
Duplicated in #70
